#ifndef SUINPUT_KEYS_H
#define SUINPUT_KEYS_H

#include <linux/input.h>

static int keyboard_keys[] = { KEY_0, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, \
    KEY_A, KEY_B, KEY_C, KEY_D, KEY_E, KEY_F, KEY_G, KEY_H, KEY_I, KEY_J, \
    KEY_K, KEY_L, KEY_M, KEY_N, KEY_O, KEY_P, KEY_Q, KEY_R, KEY_S, KEY_T, \
    KEY_U, KEY_V, KEY_W, KEY_X, KEY_Y, KEY_Z, KEY_F1, KEY_F2, KEY_F3, KEY_F4, \
    KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9, KEY_F10, KEY_F11, KEY_F12, KEY_F13, \
    KEY_F14, KEY_F15, KEY_F16, KEY_F17, KEY_F18, KEY_F19, KEY_F20, KEY_F21, KEY_F22, \
    KEY_F23, KEY_F24, KEY_KP0, KEY_KP1, KEY_KP2, KEY_KP3, KEY_KP4, KEY_KP5, KEY_KP6, \
    KEY_KP7, KEY_KP8, KEY_KP9, KEY_102ND, KEY_AGAIN, KEY_APOSTROPHE, KEY_BACKSLASH, \
    KEY_BACKSPACE, KEY_CAPSLOCK, KEY_COMMA, KEY_COMPOSE, KEY_COPY, KEY_CUT, \
    KEY_DELETE, KEY_DOT, KEY_DOWN, KEY_END, KEY_ENTER, KEY_EQUAL, KEY_ESC, KEY_FIND, \
    KEY_FRONT, KEY_GRAVE, KEY_HANGEUL, KEY_HANJA, KEY_HELP, KEY_HENKAN, KEY_HOME, \
    KEY_INSERT, KEY_KATAKANAHIRAGANA, KEY_KPASTERISK, KEY_KPCOMMA, KEY_KPDOT, KEY_KPENTER, \
    KEY_KPEQUAL, KEY_KPJPCOMMA, KEY_KPMINUS, KEY_KPPLUS, KEY_KPSLASH, KEY_LEFT, KEY_LEFTALT, \
    KEY_LEFTBRACE, KEY_LEFTCTRL, KEY_LEFTMETA, KEY_LEFTSHIFT, KEY_MINUS, KEY_MUHENKAN, KEY_MUTE, \
    KEY_NUMLOCK, KEY_OPEN, KEY_PAGEDOWN, KEY_PAGEUP, KEY_PASTE, KEY_PAUSE, KEY_POWER, KEY_PROPS, \
    KEY_RIGHT, KEY_RIGHTALT, KEY_RIGHTBRACE, KEY_RIGHTCTRL, KEY_RIGHTMETA, KEY_RIGHTSHIFT, \
    KEY_RO, KEY_SCROLLLOCK, KEY_SEMICOLON, KEY_SLASH, KEY_SPACE, KEY_STOP, KEY_SYSRQ, \
    KEY_TAB, KEY_UNDO, KEY_UNKNOWN, KEY_UP, KEY_VOLUMEDOWN, KEY_VOLUMEUP, KEY_YEN };

#endif
